package com.undercut.game.input

import com.undercut.game.hooks.HookManager
import com.undercut.game.hooks.impl.SendEventMouseClickCapture
import com.undercut.game.nxt.OMainLogicManager
import com.undercut.game.nxt.OMouseClickEntry
import java.lang.foreign.MemorySegment
import java.lang.foreign.ValueLayout.JAVA_FLOAT
import java.lang.foreign.ValueLayout.JAVA_INT
import java.lang.foreign.ValueLayout.JAVA_LONG

/**
 * Sends a synthetic mouse event to the Jagex server **without** triggering the
 * game's local click handler (no raycast, no DoAction firing) and **without
 * crafting any packet bytes in Kotlin**.
 *
 * The packet is built by Jagex's own native code (`CreatePacket` →
 * payload writers → `SendClientMessage`). We do exactly one thing differently
 * from a natural send: the X/Y/timestamp/button bytes read out of the buffer
 * entry are ours rather than the player's. On the wire it is indistinguishable
 * from a real send — same opcode, same length, same byte structure.
 *
 * Strategy (stash-drain-restore, atomic under `Bootstrap.lock`):
 *   1. Snapshot ring-buffer head, tail, and the slot's current entry bytes.
 *   2. **Bail if `head != tail`.** A non-empty buffer means real player input
 *      is already queued for this tick — the game's tick orchestrator would
 *      have called `SendEventMouseClick` itself, and adding our call would
 *      produce TWO packets in a tick when only one is natural. Trivially
 *      detectable. We silently skip and let the player's traffic flow alone.
 *   3. Write our synthetic entry into the head slot.
 *   4. Advance head so `tail != head` and the trampoline won't early-return.
 *   5. Invoke the `SendEventMouseClick` trampoline. The native function reads
 *      our entry, builds the packet, calls `SendClientMessage`. One packet on
 *      the wire, generated by Jagex's own code path.
 *   6. Restore the snapshot byte-for-byte. The local processor never observes
 *      our entry on any subsequent tick — no double-process, no duplicate.
 *
 * Caller MUST be on the game thread holding `Bootstrap.lock`. The ring buffer
 * isn't internally synchronized; the stash-drain-restore trick only works
 * because no other code runs between step 3 and step 6.
 */
object MouseClickPacketSender {
    @Volatile var packetsSent: Long = 0
        private set
    @Volatile var skippedBufferBusy: Long = 0
        private set
    @Volatile var lastSendNanos: Long = 0L
        private set

    fun sendMouseEvent(x: Int, y: Int, isClick: Boolean): Boolean {
        val clientProtAddr = SendEventMouseClickCapture.lastClientProtAddr
        if (clientProtAddr == 0L) return false  // never captured a ClientProt instance yet
        val mgr = MouseEventBuffer.managerOrNull() ?: return false

        val cap = OMainLogicManager.CLICK_BUFFER_CAPACITY
        val origHead = mgr.get(JAVA_INT, OMainLogicManager.CLICK_BUFFER_HEAD)
        val origTail = mgr.get(JAVA_INT, OMainLogicManager.CLICK_BUFFER_TAIL)

        // Duplicate-avoidance: if the player just clicked / moved, their entries
        // are already in the buffer and the game's natural tick will drain them
        // this very tick. We must NOT add another packet on top — that doubles
        // the per-tick send count, which is the easiest possible bot signature.
        if (origHead != origTail) {
            skippedBufferBusy++
            return false
        }

        val writeIdx = ((origHead % cap) + cap) % cap
        val entryOffset = OMainLogicManager.CLICK_BUFFER_BASE + writeIdx * OMainLogicManager.CLICK_ENTRY_SIZE
        val savedFlag = mgr.get(JAVA_INT, entryOffset + OMouseClickEntry.BUTTON_FLAG)
        val savedY = mgr.get(JAVA_FLOAT, entryOffset + OMouseClickEntry.Y)
        val savedX = mgr.get(JAVA_FLOAT, entryOffset + OMouseClickEntry.X)
        val savedTs = mgr.get(JAVA_LONG, entryOffset + OMouseClickEntry.TIMESTAMP_MS)

        try {
            mgr.set(JAVA_INT, entryOffset + OMouseClickEntry.BUTTON_FLAG, if (isClick) 1 else 0)
            mgr.set(JAVA_FLOAT, entryOffset + OMouseClickEntry.Y, y.toFloat())
            mgr.set(JAVA_FLOAT, entryOffset + OMouseClickEntry.X, x.toFloat())
            mgr.set(JAVA_LONG, entryOffset + OMouseClickEntry.TIMESTAMP_MS, System.currentTimeMillis())

            val nextHead = if (origHead + 1 >= cap) 0 else origHead + 1
            mgr.set(JAVA_INT, OMainLogicManager.CLICK_BUFFER_HEAD, nextHead)

            val clientProt = MemorySegment.ofAddress(clientProtAddr).reinterpret(0x40)
            HookManager.trampoline(SendEventMouseClickCapture::sendEventMouseClickHook.name)
                .invokeExact(clientProt)

            packetsSent++
            lastSendNanos = System.nanoTime()
            return true
        } catch (e: Throwable) {
            e.printStackTrace()
            return false
        } finally {
            mgr.set(JAVA_INT, entryOffset + OMouseClickEntry.BUTTON_FLAG, savedFlag)
            mgr.set(JAVA_FLOAT, entryOffset + OMouseClickEntry.Y, savedY)
            mgr.set(JAVA_FLOAT, entryOffset + OMouseClickEntry.X, savedX)
            mgr.set(JAVA_LONG, entryOffset + OMouseClickEntry.TIMESTAMP_MS, savedTs)
            mgr.set(JAVA_INT, OMainLogicManager.CLICK_BUFFER_HEAD, origHead)
            mgr.set(JAVA_INT, OMainLogicManager.CLICK_BUFFER_TAIL, origTail)
        }
    }
}
