local Quest = require("core.quest")
local QuestStep = require("core.queststep")
local Condition = require("core.condition")
local Action = require("core.action")
local Models = require("util.models")
local Enums = require("core.enums")

---@type QuestStep[]
local steps = {
  {
    text = "Talk to Explorer Jack who is located in a house west of the Lumbridge General Store.",
    title = "Getting started",
    neededItems = {},
    recommendedItems = {},
    postconditions = { Condition.QuestInterfaceOpen:new() },
    actions = { Action.ConversationHighlight:new("You mentioned a quest?") },
  },
  {
    text = "[Accept Quest]",
    postconditions = { Condition.QuestStarted:new() },
    actions = {
      Action.ConversationHighlight:new("How do I get to the Land of Snow?"),
      Action.ConversationHighlight:new("Actually, never mind."),
    },
  },
  { text = "Go to the Wizards' Tower which is located south of Draynor Village." },
  {
    text = "Talk to Wizard Isidor who is in the west room on the 1st floor[UK]2nd floor[US] of the tower.",
    actions = { Action.ConversationHighlight:new("I'm a friend of Explorer Jack and need teleporting.") },
  },
  { text = "South", title = "The Land of Snow" },
  { text = "North-East" },
  { text = "East" },
  { text = "North-east" },
  { text = "East" },
  { text = "North" },
  { text = "South-east" },
  { text = "East" },
  { text = "South-west" },
  { text = "East" },
  { text = "North" },
  { text = "East" },
  { text = "North" },
  { text = "South-east" },
  { text = "North" },
  { text = "East" },
  { text = "South" },
  { text = "East" },
  { text = "North-east" },
  { text = "North" },
  { text = "East" },
  { text = "North" },
  { text = "South-east" },
  { text = "South-west" },
  { text = "East" },
  { text = "East" },
  { text = "North-west" },
  { text = "East" },
  { text = "South-west" },
  { text = "East" },
  {
    text = "East<ul><li>You will move to the next room and immediately get pushed back by the yeti's scream. This is required to be able to move the blocks.</li></ul>",
  },
  { text = "South-east" },
  { text = "East" },
  { text = "South" },
  { text = "Push block west" },
  { text = "South" },
  { text = "North-west" },
  { text = "Push block north" },
  { text = "North" },
  { text = "West" },
  { text = "North-east" },
  { text = "Push block east" },
  { text = "East" },
  { text = "South" },
  { text = "East" },
  { text = "Push block north (block is now in place)" },
  { text = "West" },
  { text = "South" },
  { text = "South" },
  { text = "East" },
  { text = "North" },
  { text = "Push block east" },
  { text = "East" },
  { text = "South" },
  { text = "East" },
  { text = "Push block north" },
  { text = "North" },
  { text = "East" },
  { text = "North" },
  { text = "Push block west" },
  { text = "South" },
  { text = "West" },
  { text = "Push block north" },
  { text = "North-east" },
  { text = "North" },
  { text = "Push block west" },
  { text = "South-west" },
  { text = "West" },
  { text = "North-east" },
  { text = "Push block north (block is now in place)" },
  { text = "West" },
  { text = "South" },
  { text = "Exit-room archway back to the fifth cavern." },
  { text = "North-East" },
  { text = "North-West" },
  { text = "East" },
  { text = "Squeeze-through crevice." },
  {
    text = "Go to the crevice to the east (optionally, you can clear the wall just south of the crevice for 20,000 Woodcutting experience. This requires level 80 Woodcutting and is part of the Caving into the Gains achievement).",
  },
  { text = "Squeeze-through crevice." },
  { text = "Study the nearby wall." },
  { text = "Shout-in the pipe." },
  { text = "Go back through both crevices." },
  { text = "West" },
  { text = "South-east" },
  { text = "East" },
  { text = "Go east back into the Yeti room." },
  { text = "Pick up the stones." },
  { text = "Exit west." },
  { text = "Right-click exit-cave on the cavern archway." },
  { text = "Let the imps enchant the stones.", title = "Finishing up", neededItems = {}, recommendedItems = {} },
  {
    text = "Return to Explorer Jack in Lumbridge.",
    actions = {
      Action.ConversationHighlight:new("About Myths of the White Lands..."),
      Action.ConversationHighlight:new("[Any option]"),
    },
  },
  { text = "Quest complete!" },
}

return Quest:new({
  name = "Myths of the White Lands",
  steps = steps,
  timeline = Enums.timeline.pathfinder,
  members = false,
  length = Enums.length.medium,
  releaseDate = 1229385600,
  prereqQuests = {},
})
