package com.undercut.script.impl.trent

import com.undercut.script.Script
import com.undercut.script.ScriptDescription
import com.undercut.script.api.continueDialogueContaining

@ScriptDescription(
    name = "Meg",
    version = "1.0.0",
    author = "Trent",
    description = "Answer meg right now."
)
class Meg : Script() {
    override suspend fun loop() {
        excellent.forEach { if (continueDialogueContaining(it)) return delay(850, 100) }
        good.forEach { if (continueDialogueContaining(it)) return delay(850, 100) }
        delay(350, 100)
    }
}

private val excellent = setOf(
    "They'll probably use sound to track prey.",
    "Dance on the ground to attract them.",
    "Take the most valuable pieces with you.",
    "Keep to the shadows and cover yourself in dark colours.",
    "Research them carefully",
    "The jungles would be a good place to hide it.",
    "Look in the caves around Karamja.",
    "I hear it's near Port Phasmatys.",
    "Work on your agility - it'll help.",
    "They're just burnt lobsters, Meg.",
    "Someone was trying to trick you, Meg.",
    "Reconsider. Witches can be unpredictable.",
    "Make sure you have a strong magic defence.",
    "Learn the enchantment that makes it work.",
    "Set a trap beforehand.",
    "Make sure your farming skill is up to scratch.",
    "Look out for the rare breeds of jadinko.",
    "Necromancy seems to have nasty side effects. Be careful.",
    "Don't go alone.",
    "Look for a vampyre resistance group.",
    "Find a good disguise.",
    "Leave that to the Wizards' Tower.",
    "None that I know of.",
    "Treat the sword as an extension of your arm.",
    "Dogs are loyal and have great noses.",
    "Get some good quality lockpicks.",
    "Aim for their arm rather than their hand.",
    "Keep your distance",
    "A strong machete.",
    "Get a mining helmet.",
    "Enchanting doesn't work that way.",
    "Insects don't like smoke.",
    "Scope out the arena first.",
    "Bring a group.",
    "Find a path nearby.",
    "Find out why the ghosts are haunting it.",
    "Father Urhney is a skilled exorcist. He can help.",
    "Try to find out what's keeping the spirits trapped.",
    "Distract them with something shiny first.",
    "Try attacking from a distance. They tend to be melee-based.",
    "Fighting rock crabs is good combat training.",
    "Their rock forms can be identified, if you're observant.",
    "I hear there is a magic weapon that will help.",
    "Attack from a distance.",
    "Vampyres don't like silver.",
    "I hear you need a potion to defeat them.",
    "You'd be better off using a crossbow.",
    "Be careful. A weapon like that will be guarded.",
    "Be sure you can trust your friend.",
    "Study them carefully. It'll come back to you.",
    "Watch out for ghasts.",
    "Look for trees that aren't rotten.",
    "Ask Father Aereck about a ghost for a good reward.",
    "The Salvation auras can be useful.",
    "I think you should start smaller, Meg.",
    "Why not get some help on this one?",
    "Use a long rod.",
    "Don't go in the water.",
    "Find a loophole in the contract.",
    "I've heard it's near a furnace.",
    "Get on Darren Lightfinger's good side first.",
    "Just use one of the trees at the canoe station.",
    "Very special circumstances create rune essence. Look for those.",
    "Honestly, it's unlikely you'll find one.",
    "Sneak up on them from behind.",
    "Draw a line in front of their beaks to hypnotise them.",
    "Make sure you're good enough at summoning to keep one.",
    "A squirrel is for life, not just for a whim.",
    "Tread carefully. It might be a trap.",
    "It's never wise to pay money up-front like that.",
    "Something durable, which still allows freedom of movement.",
    "Fish are generally easy to come by.",
    "Use a powerful bow to take him out from range.",
    "Only you can answer that."
)

private val good = setOf(
    "Use kebbits as bait",
    "I think your friend is pulling your leg, Meg",
    "Don't get carried away by greed. Take what you need",
    "Keep to the shadows",
    "Try setting them off remotely",
    "Sneak into the Legends' Guild and see if they know",
    "Investigate sources of magic",
    "It's called the Ectofuntus, Meg",
    "You'll need bones, pots and buckets",
    "Don't go Meg. They're lies",
    "Were they very crispy?",
    "Bring some allies for support",
    "Be stealthy; wait till she leaves",
    "You could help the needy during droughts",
    "Get yourself the homeground advantage",
    "Make juju hunter flasks",
    "Bring hunter potions",
    "Bring equipment that's good against undead",
    "Keep teleport runes handy",
    "Have a quick escape plan",
    "Vampyres are hard to fool",
    "Try and bargain with one, rather than bind it",
    "I guess unicorns, if you can tame them",
    "Remember - the sword can do more than just stab",
    "Birds have a great range of travel",
    "Locate alternative entrances",
    "Use a crossbow for greater accuracy",
    "Carefully - treat the hook as a weapon",
    "A sharp sword",
    "Speak to the dwarves for suggestions",
    "You'll need an enchantment spell",
    "When in a tent, cover the gaps with netting",
    "Research your opponent",
    "Arm yourself with powerful weapons",
    "Scale the cliffside, not the fall",
    "Talk to an exorcist first",
    "An amulet of ghostspeak would be useful",
    "Give them a proper burial",
    "Goblins are fairly weak. Just be brave",
    "Strike quickly, before they can strike you",
    "Pickaxes are good against them",
    "They have a strong defence. Be careful",
    "Try diplomacy first",
    "Bring food. They can hit hard",
    "Be careful. Vampyres are very dangerous",
    "You'll need a special weapon to defeat them",
    "Arrows aren't generally good at holding weight",
    "Saradomin's followers may know something",
    "Ask around. Rumours are occasionally based on truth",
    "Work backwards",
    "Don't wear anything flammable",
    "Set several traps to be sure",
    "Imps drop ashes that you can scatter",
    "There are lots of goblins to get bones from",
    "I'm not sure that fish is real, Meg",
    "Be calm and don't panic",
    "A disguise is always a good idea",
    "Take the wealth in small batches over time",
    "Stay above the ground",
    "Mark where you've been so you can get back",
    "Arm yourself. The locals might not be friendly",
    "Cook them immediately so they don't freak you out",
    "Wear gloves so you don't have to feel them",
    "Disguise the traps as best you can",
    "Consider putting seeds on the trap",
    "Be quiet and keep still. You don't want to spook them",
    "Make sure you're using the right trap",
    "Don't panic. Undead are slow and stupid",
    "Look for a binding spell",
    "Keep quiet. They're easily spooked",
    "Just keep focused and prepare to lose a few",
    "Whatever you do, don't agree to anything",
    "Be careful",
    "Dig a tunnel with a spoon",
    "Hide under the bed",
    "Kill some goblins and bury their bones",
    "Be quiet and polite. It is a place of worship, after all",
    "Set a trap using meat and a net",
    "Find a way to trap them",
    "Bind the demon to your service",
    "Accept any 'job' offers the guild offers you",
    "Consider the art of disguise",
    "Try oak - sturdy, and not too expensive",
    "Rune essence absorbs magic. Look for weird side effects",
    "Look for high concentrations of magic",
    "Try not to show fear",
    "Strike quickly. It gets it over with faster",
    "Nuts. I don't really need to say more",
    "Be careful. They can scratch",
    "You need to find better friends",
    "I think your 'friend' may have tricked you",
    "Something that provides all-round protection",
    "Rabbits are tasty and easy to catch",
    "Take him out from the shadows",
    "Why follow just one god?"
)