//! Selects the active recorder offset revision and wires the migrator-generated
//! `offsets_<rev>.rs` into the build as the struct/derived-offset source of truth.
//!
//! The mac offset migrator (`re-resources/ghidra-scripts/RS3RecorderUpdaterMac.java`)
//! emits `re-resources/updater/recorder/offsets_<rev>.rs` — Rust `pub const`
//! values for every recorder struct/derived offset, with drift detection. Rather
//! than copy those literals into `src/offsets/` by hand, this build script picks
//! the active rev and writes a one-line shim into `OUT_DIR` that `include!`s the
//! canonical generated file. `src/offsets/mod.rs` then
//! `include!(concat!(env!("OUT_DIR"), "/offset_include.rs"))` and re-exports it.
//!
//! PER-REV FLOW (the payoff): regenerate `offsets_<newrev>.rs` with the migrator,
//! then point the active rev at it — either bump `DEFAULT_OFFSET_REV` below (the
//! one-liner) or build with `DARKAN_RECORDER_OFFSET_REV=<newrev>`. Rebuild. No
//! offset VALUE is ever hand-edited.

use std::path::{Path, PathBuf};

/// The active offset revision when `DARKAN_RECORDER_OFFSET_REV` is not set.
/// One-line bump per client rev (e.g. `"949"`, `"949-1"`).
const DEFAULT_OFFSET_REV: &str = "948-5";

fn main() {
    // Rebuild whenever the rev selector changes.
    println!("cargo:rerun-if-env-changed=DARKAN_RECORDER_OFFSET_REV");

    let rev = std::env::var("DARKAN_RECORDER_OFFSET_REV")
        .ok()
        .filter(|s| !s.trim().is_empty())
        .unwrap_or_else(|| DEFAULT_OFFSET_REV.to_string());

    // CARGO_MANIFEST_DIR == client/launcher/recorder-mac → repo root is three up.
    let manifest_dir = PathBuf::from(env_var("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir
        .ancestors()
        .nth(3)
        .unwrap_or(&manifest_dir)
        .to_path_buf();

    let generated = repo_root
        .join("re-resources")
        .join("updater")
        .join("recorder")
        .join(format!("offsets_{rev}.rs"));

    if !generated.is_file() {
        panic!(
            "recorder offsets source not found for rev {rev:?}: {}\n\
             Generate it with the mac offset migrator (RS3RecorderUpdaterMac \
             import/selftest), or set DARKAN_RECORDER_OFFSET_REV to an existing rev.",
            generated.display()
        );
    }

    // Rebuild whenever the selected generated offsets file changes.
    println!("cargo:rerun-if-changed={}", generated.display());
    // Also rerun this script if it itself changes (so a DEFAULT_OFFSET_REV bump
    // is picked up even when the env var is unset).
    println!("cargo:rerun-if-changed=build.rs");

    // Read the generated file and emit its BODY (the `pub mod`/`pub const` items)
    // into OUT_DIR, dropping the migrator's file-level header (the `//!` inner doc
    // lines + the `#![allow(dead_code)]` inner attribute). Those are illegal at an
    // `include!` site nested inside `mod gen { ... }` ("inner attribute not
    // permitted following an outer doc comment"); the enclosing module supplies
    // the `#[allow(dead_code)]` itself. We strip ONLY the leading comment/inner-
    // attribute header — every offset VALUE line is carried through verbatim, so
    // the generated file remains the untouched source of truth.
    let generated_src = std::fs::read_to_string(&generated)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", generated.display()));
    let body = strip_file_header(&generated_src);

    let shim = format!(
        "// @generated by build.rs — active recorder offset rev: {rev}\n\
         // Body of re-resources/updater/recorder/offsets_{rev}.rs (migrator output),\n\
         // file-level header stripped so it can be include!'d inside `mod gen`.\n\
         // Offset VALUES are carried through verbatim — the generated file is the\n\
         // source of truth; this is a transport shim only.\n\
         {body}"
    );

    let out_dir = PathBuf::from(env_var("OUT_DIR"));
    let shim_path = out_dir.join("offset_include.rs");
    write_if_changed(&shim_path, &shim);

    // Surface the active rev for log/debug builds that want to print it.
    println!("cargo:rustc-env=DARKAN_RECORDER_ACTIVE_OFFSET_REV={rev}");
}

fn env_var(key: &str) -> String {
    std::env::var(key).unwrap_or_else(|_| panic!("{key} not set by cargo"))
}

/// Drop the migrator file's leading header — blank lines, `//`/`//!` comments,
/// and `#![...]` inner attributes — keeping everything from the first real item
/// (the first `pub mod`) onward verbatim. This is purely a transport adjustment
/// for `include!`ing inside a nested module; no offset value is touched. We only
/// consume the CONTIGUOUS leading header, so a `//` comment attached to a later
/// item is preserved.
fn strip_file_header(src: &str) -> String {
    let mut lines = src.lines().peekable();
    while let Some(line) = lines.peek() {
        let t = line.trim_start();
        if t.is_empty() || t.starts_with("//") || t.starts_with("#![") {
            lines.next();
        } else {
            break;
        }
    }
    let mut out: String = lines.collect::<Vec<_>>().join("\n");
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Write only when the content differs, so an unchanged rev does not bump mtimes
/// and trigger spurious downstream rebuilds.
fn write_if_changed(path: &Path, content: &str) {
    if let Ok(existing) = std::fs::read_to_string(path) {
        if existing == content {
            return;
        }
    }
    std::fs::write(path, content)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", path.display()));
}
